/*
GAME RULES:

- The game has 2 players, playing in rounds
- In each turn, a player rolls a dice as many times as he whishes. Each result get added to his ROUND score
- BUT, if the player rolls a 1, all his ROUND score gets lost. After that, it's the next player's turn
- The player can choose to 'Hold', which means that his ROUND score gets added to his GLBAL score. After that, it's the next player's turn
- The first player to reach 100 points on GLOBAL score wins the game

*/

var scores, roundScore, activePlayer;

scores=[0,0];   //array for storing the score of each player of game
roundScore = 0;  //varible for storing the score of each player in a round
activePlayer = 0;  //varible for determining the active player


 
 
//document.querySelector('#current-' + activePlayer).textContent = dice;
//document.querySelector('#current-' + activePlayer).innerHTML = '<em>'+ dice+ '</em>';

// var x = document.querySelector('#score-0').textContent;
// console.log(x);

document.getElementById('score-0').textContent=0;
document.getElementById('current-0').textContent=0;
document.getElementById('score-1').textContent=0;
document.getElementById('current-1').textContent=0;

document.querySelector('.dice').style.display = 'none';


/* 
for generating the random number between 1 and 6.
Math.floor() function used to convert decimal number to integer or whole number.
Math.random() function to generate random numbers between 0 and 1.
number generated by random() function multiplied by 6 and addition of 1 to get 
numbers between 1 and 6.
*/
document.querySelector('.btn-roll').addEventListener('click', function(){
    
    //Generating random numbers
    var dice = Math.floor(Math.random() * 6) +1; 

    // Display the result
    var diceDOM = document.querySelector('.dice');
    diceDOM.style.display = 'block';
    diceDOM.src = 'dice-' + dice + '.png';


    //if 1 is not rolled in dice, add the dice score to round score and update the score
    //to round score
    if(dice !==1){

        roundScore = roundScore + dice;
        document.querySelector('#current-'+ activePlayer).textContent = roundScore;

    }
    else{ 
    //if 1 is rolled, 
    // - change the active player
    // - reset the round score to zero
    // - toggle the "active" class between player 1 and player 2    

        
        //if 0 was active player, 1 is made active player and vice-versa 
        activePlayer === 0? activePlayer = 1: activePlayer = 0;
        //resetting round score to zero
        roundScore = 0;

        // when 1 is rolled in dice, updating round scores to zero
        document.getElementById('current-0').textContent = '0';
        document.getElementById('current-1').textContent = '0';

        //toggling the active player between player 1 and player 2, to indicate the 
        //active player through specific change in color of panel of active player
        document.querySelector('.player-0-panel').classList.toggle('active');
        document.querySelector('.player-1-panel').classList.toggle('active');

        //for disappearance of dice after 1 is rolled in dice
        document.querySelector('.dice').style.display='none';
    }

});